version: '3.8'

services:
  ml-pipeline:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI:-https://dagshub.com/basswala/machinelearningpipeline.mlflow}
      - MLFLOW_TRACKING_USERNAME=${MLFLOW_TRACKING_USERNAME}
      - MLFLOW_TRACKING_PASSWORD=${MLFLOW_TRACKING_PASSWORD}
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add MLflow UI if using local tracking
  mlflow-ui:
    image: python:3.11-slim
    ports:
      - "5000:5000"
    command: >
      sh -c "pip install mlflow && 
             mlflow server 
             --backend-store-uri sqlite:///mlflow.db 
             --default-artifact-root ./mlruns 
             --host 0.0.0.0 
             --port 5000"
    volumes:
      - mlflow-data:/app
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
    profiles:
      - mlflow
